name: Test workflow
on:
  push:
    branches:
      - feature
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calling REST API to create a repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/user/repos \
          -d '{"name":"test-repo-13","description":"created this repo through rest call","homepage":"https://github.com","private":false,"is_template":true ,"auto_init": true,"gitignore_template":"Android"}'
   
   
