name: Test workflow
on:
  push:
    branches:
      - feature
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calling REST API to create a repo
        run: |
          curl --location --request POST 'https://api.github.com/user/repos' \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer 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' \
            --data-raw '{
                "name":"test-repo-13",
                "auto_init": true,
                "description":"created this repo through rest call",
                "gitignore_template":"Android"
            }'
   
   
